version: "2"

services:
    master:
        image: kaldi-gstreamer-master
        container_name: asr-master
        build:
            context: docker
            dockerfile: docker/Dockerfile.master
        ports:
            - "5477:80"

    worker:
        image: kaldi-gstreamer-worker
        container_name: asr-worker
        build:
            context: docker
            dockerfile: docker/Dockerfile.worker
        volumes:
            - ./kaldi-gstreamer-server:/opt/models
